In [1]:
import pandas as pd

pd.read_csv('top_three_genres.csv')

           studio  month  day            genre  domestic_gross
0              BV      6  mid     comedy_gross     415000000.0
1            P/DW      5  mid     comedy_gross     238700000.0
2              BV     11  end     comedy_gross     200800000.0
3            Uni.      7  beg     comedy_gross     251500000.0
4            P/DW     11  beg     comedy_gross     148400000.0
5            Uni.     12  end     comedy_gross     148400000.0
6         WB (NL)      5  end     comedy_gross      95300000.0
7            Sony      6  end     comedy_gross     162000000.0
8             Fox     12  end     comedy_gross      42800000.0
9         WB (NL)      2  mid     comedy_gross     110500000.0
10             WB     11  beg     comedy_gross     100500000.0
11             WB     12  mid     comedy_gross     100200000.0
12           Sony      8  beg     comedy_gross     119200000.0
13            Fox      4  beg     comedy_gross      98700000.0
14           Sony      3  mid     comedy_gross      67099999.0
15             WB      7  end     comedy_gross      43600000.0
16            Fox      1  end     comedy_gross      60000000.0
17            LGF      6  beg     comedy_gross      47100000.0
18            LGF      4  mid     comedy_gross      48100000.0
19           Uni.      6  beg     comedy_gross      61000000.0
20           P/DW      7  end     comedy_gross      73000000.0
21            Fox      6  beg     comedy_gross      33600000.0
22         W/Dim.      8  mid     comedy_gross      25000000.0
23            Fox      8  mid     comedy_gross      36700000.0
24           Sum.      5  mid     comedy_gross      53000000.0
25            Fox      3  mid     comedy_gross      64000000.0
26           SGem      9  mid     comedy_gross      58400000.0
27            MGM      3  end     comedy_gross      50300000.0
28           Par.     11  beg     comedy_gross      31000000.0
29             WB      2  end     comedy_gross      44900000.0
...           ...    ...  ...              ...             ...
1352         Sony      6  end  adventure_gross     167500000.0
1353         Par.     12  end  adventure_gross     127200000.0
1354           BV      5  end  adventure_gross     213800000.0
1355         Sony      2  beg  adventure_gross     115300000.0
1356         Uni.      7  mid  adventure_gross      68400000.0
1357           WB      3  mid  adventure_gross      58300000.0
1358           WB      1  mid  adventure_gross      40900000.0
1359           WB      9  end  adventure_gross      83200000.0
1360           BV     11  beg  adventure_gross      54900000.0
1361         Uni.     10  end  adventure_gross       4400000.0
1362           BV      3  beg  adventure_gross     100500000.0
1363         Sony     10  mid  adventure_gross      46700000.0
1364         Par.      3  end  adventure_gross      43200000.0
1365         Uni.     12  mid  adventure_gross      16000000.0
1366    Annapurna      1  mid  adventure_gross      47800000.0
1367          LGF      8  beg  adventure_gross      33600000.0
1368          STX      8  mid  adventure_gross      36100000.0
1369          STX      7  beg  adventure_gross      31400000.0
1370          LGF      2  mid  adventure_gross       8300000.0
1371          VPD      7  end  adventure_gross        289000.0
1372         Par.     11  beg  adventure_gross      21700000.0
1373          Fox      8  beg  adventure_gross      12700000.0
1374  Global Road      5  mid  adventure_gross      17900000.0
1375  Global Road      9  beg  adventure_gross       9600000.0
1376       Affirm      3  end  adventure_gross      17600000.0
1377        ENTMP      3  beg  adventure_gross       6100000.0
1378        Scre.     11  end  adventure_gross         29500.0
1379           VE      2  beg  adventure_gross        491000.0
1380          A24      4  beg  adventure_gross       1200000.0
1381        Orch.      3  mid  adventure_gross        112000.0

[1382 rows x 5 columns]